name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Display Python version
      run: python -c "import sys; print(f'Python {sys.version}')"
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
        
    - name: List files (debug)
      run: ls -la
      
    - name: Run basic tests
      run: |
        python -c "import sys; print('Python imports working')"
        if [ -d "tests" ]; then
          pytest tests/ -v || echo "Tests failed but continuing..."
        else
          echo "No tests directory found"
        fi